-- =============================================================================
-- Camp Support — Supabase Schema
-- Run this in the Supabase SQL Editor (Project → SQL Editor → New Query)
-- =============================================================================

-- Enable pgcrypto for hashing
create extension if not exists pgcrypto;

-- ── 1. Staff table ────────────────────────────────────────────────────────────
create table if not exists public.staff (
  id             bigint generated by default as identity primary key,
  name           text        not null,
  pin_access     text        not null unique,   -- hashed PIN
  contact_number text,                          -- staff contact / phone number
  is_admin       boolean     not null default false,  -- admin flag
  created_at     timestamptz not null default now()
);

-- Add contact_number and is_admin to existing installations
alter table public.staff add column if not exists contact_number text;
alter table public.staff add column if not exists is_admin boolean not null default false;

-- Trigger to automatically hash pin_access on insert
create or replace function public.hash_staff_pin()
returns trigger as $$
begin
  if (tg_op = 'INSERT' or new.pin_access <> old.pin_access) then
    new.pin_access = crypt(new.pin_access, gen_salt('bf'));
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists tr_hash_staff_pin on public.staff;
create trigger tr_hash_staff_pin
  before insert or update on public.staff
  for each row execute function public.hash_staff_pin();

-- Seed test staff members (Trigger will handle hashing)
do $$
begin
  if not exists (select 1 from public.staff) then
    insert into public.staff (name, pin_access, contact_number, is_admin) values
      ('Admin User',  '1234', '+91-99001-00001', true),
      ('Staff Alpha', '5678', '+91-99001-00002', false);
  end if;
end $$;


-- ── 2. Tickets table ──────────────────────────────────────────────────────────
create table if not exists public.tickets (
  id                 bigint generated by default as identity primary key,
  issue_description  text        not null,
  location           text        not null,
  status             text        not null default 'open'
                        check (status in ('open', 'pending', 'resolved')),
  priority           text        not null default 'normal'
                        check (priority in ('low', 'normal', 'high', 'critical')),
  creator_name       text        not null,
  assigned_to        text,                  -- name or PIN of assignee
  created_at         timestamptz not null default now()
);

-- Ensure the issue_description check constraint exists on existing installations
do $$
begin
  if not exists (
    select 1 from pg_constraint 
    where conname = 'tickets_issue_description_check'
  ) then
    alter table public.tickets 
    add constraint tickets_issue_description_check 
    check (length(trim(issue_description)) > 0);
  end if;
end $$;

-- Add priority to existing installations
alter table public.tickets add column if not exists priority text not null default 'normal'
  check (priority in ('low', 'normal', 'high', 'critical'));


-- ── 3. Row Level Security ─────────────────────────────────────────────────────
-- Enable RLS on both tables
alter table public.staff   enable row level security;
alter table public.tickets enable row level security;

-- Staff Table Policies
-- Deny all public access to staff table (select/insert/update/delete)

-- Tickets Table Policies
drop policy if exists "tickets_insert_anon" on public.tickets;
drop policy if exists "tickets_read_all" on public.tickets;
drop policy if exists "tickets_update_creator" on public.tickets;

create policy "tickets_insert_anon" on public.tickets for insert with check (true);
create policy "tickets_read_all" on public.tickets for select using (true);
create policy "tickets_update_creator" on public.tickets for update using (true);


-- ── 4. Secure PIN Verification (RPC) ──────────────────────────────────────────
-- DROP first so return type can always be changed on re-runs
drop function if exists public.verify_staff_pin(text);
create or replace function public.verify_staff_pin(input_pin text)
returns table(id bigint, name text, is_admin boolean, contact_number text)
language sql security definer stable
as $$
  select id, name, is_admin, contact_number
  from public.staff
  where pin_access = crypt(input_pin, pin_access)
  limit 1;
$$;

-- ── 5. Secure PIN Reset (RPC) ─────────────────────────────────────────────────
create or replace function public.reset_staff_pin(staff_id bigint, new_pin text)
returns boolean
language plpgsql
security definer
as $$
begin
  -- Note: Trigger will automatically hash the new_pin
  update public.staff
  set pin_access = new_pin
  where id = staff_id;
  
  return found;
end;
$$;


-- ── 6. Enable Realtime on tickets ─────────────────────────────────────────────
do $$
begin
  if not exists (
    select 1 from pg_publication_tables 
    where pubname = 'supabase_realtime' 
    and schemaname = 'public' 
    and tablename = 'tickets'
  ) then
    alter publication supabase_realtime add table public.tickets;
  end if;
end $$;
