-- =============================================================================
-- Camp Support — Supabase Schema
-- Run this in the Supabase SQL Editor (Project → SQL Editor → New Query)
-- =============================================================================

-- ── 0. Extensions ─────────────────────────────────────────────────────────────
-- pgcrypto is pre-installed on Supabase — just enable it
create extension if not exists pgcrypto;

-- ── 1. Staff table ────────────────────────────────────────────────────────────
create table if not exists public.staff (
  id             bigint generated by default as identity primary key,
  name           text        not null,
  pin_access     text        not null unique,   -- the PIN used to log in
  contact_number text,                          -- staff contact / phone number
  is_admin       boolean     not null default false,  -- admin flag
  created_at     timestamptz not null default now()
);

-- Add contact_number and is_admin to existing installations
alter table public.staff add column if not exists contact_number text;
alter table public.staff add column if not exists is_admin boolean not null default false;

-- ── Trigger: auto-bcrypt any plain-text PIN on INSERT or UPDATE ───────────────
create or replace function public.hash_pin_before_save()
returns trigger language plpgsql as $$
begin
  -- Only hash if the value is NOT already a bcrypt hash (starts with $2)
  if NEW.pin_access not like '$2%' then
    NEW.pin_access := crypt(NEW.pin_access, gen_salt('bf', 6));
  end if;
  return NEW;
end $$;

drop trigger if exists trg_hash_pin on public.staff;
create trigger trg_hash_pin
  before insert or update of pin_access on public.staff
  for each row execute function public.hash_pin_before_save();

-- ── RPC: verify a PIN against the stored bcrypt hash ──────────────────────────
-- DROP first so return type can always be changed on re-runs
drop function if exists public.verify_staff_pin(text);
create or replace function public.verify_staff_pin(input_pin text)
returns table(id bigint, name text, is_admin boolean, contact_number text)
language sql security definer
stable
as $$
  select id, name, is_admin, contact_number
  from public.staff
  where pin_access = crypt(input_pin, pin_access)
  limit 1;
$$;

-- Seed admin + a test staff member — trigger will bcrypt the plain-text PINs
-- ON CONFLICT: update name/is_admin but NOT pin_access (avoids double-hashing)
insert into public.staff (name, pin_access, contact_number, is_admin) values
  ('Admin User',  '0000', '+91-99001-00001', true),
  ('Staff Alpha', '5678', '+91-99001-00002', false)
on conflict (pin_access) do update
  set is_admin = excluded.is_admin,
      name     = excluded.name
  where public.staff.pin_access like '$2%'; -- only update metadata, never rehash


-- ── 2. Tickets table ──────────────────────────────────────────────────────────
create table if not exists public.tickets (
  id                 bigint generated by default as identity primary key,
  issue_description  text        not null,
  location           text        not null,
  status             text        not null default 'open'
                        check (status in ('open', 'pending', 'resolved')),
  priority           text        not null default 'normal'
                        check (priority in ('low', 'normal', 'high', 'critical')),
  creator_name       text        not null,
  assigned_to        text,                  -- name or PIN of assignee
  created_at         timestamptz not null default now()
);

-- Add priority to existing installations
alter table public.tickets add column if not exists priority text not null default 'normal'
  check (priority in ('low', 'normal', 'high', 'critical'));


-- ── 3. Row Level Security ─────────────────────────────────────────────────────
-- Enable RLS on both tables
alter table public.staff   enable row level security;
alter table public.tickets enable row level security;

-- Drop existing policies first so this script is safe to re-run
drop policy if exists "staff_read_all"     on public.staff;
drop policy if exists "staff_insert_all"   on public.staff;
drop policy if exists "staff_update_all"   on public.staff;
drop policy if exists "staff_delete_all"   on public.staff;
drop policy if exists "tickets_read_all"   on public.tickets;
drop policy if exists "tickets_insert_all" on public.tickets;
drop policy if exists "tickets_update_all" on public.tickets;
drop policy if exists "tickets_delete_all" on public.tickets;

-- Allow anon + authenticated to READ staff (needed for PIN auth check)
create policy "staff_read_all"   on public.staff for select using (true);

-- Allow anon + authenticated to INSERT/UPDATE/DELETE staff (admin portal)
create policy "staff_insert_all" on public.staff for insert with check (true);
create policy "staff_update_all" on public.staff for update using (true);
create policy "staff_delete_all" on public.staff for delete using (true);

-- Allow anon + authenticated full access to tickets
create policy "tickets_read_all"   on public.tickets for select using (true);
create policy "tickets_insert_all" on public.tickets for insert with check (true);
create policy "tickets_update_all" on public.tickets for update using (true);
create policy "tickets_delete_all" on public.tickets for delete using (true);


-- ── 4. Enable Realtime on tickets ─────────────────────────────────────────────
-- Safe to re-run: only adds if not already a member
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'tickets'
  ) then
    alter publication supabase_realtime add table public.tickets;
  end if;
end $$;
