-- =============================================================================
-- Camp Support — Supabase Schema
-- Run this in the Supabase SQL Editor (Project → SQL Editor → New Query)
-- =============================================================================

-- Enable pgcrypto for hashing
create extension if not exists pgcrypto;

-- ── 1. Staff table ────────────────────────────────────────────────────────────
create table if not exists public.staff (
  id             bigint generated by default as identity primary key,
  name           text        not null,
  pin_access     text        not null unique,   -- hashed PIN
  contact_number text,                          -- staff contact / phone number
  is_admin       boolean     not null default false,  -- admin flag
  created_at     timestamptz not null default now()
);

-- Add contact_number and is_admin to existing installations
alter table public.staff add column if not exists contact_number text;
alter table public.staff add column if not exists is_admin boolean not null default false;

-- Trigger to automatically hash pin_access on insert
create or replace function public.hash_staff_pin()
returns trigger as $$
begin
  if (tg_op = 'INSERT' or new.pin_access <> old.pin_access) then
    new.pin_access = crypt(new.pin_access, gen_salt('bf'));
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists tr_hash_staff_pin on public.staff;
create trigger tr_hash_staff_pin
  before insert or update on public.staff
  for each row execute function public.hash_staff_pin();

-- Seed test staff members (Trigger will handle hashing)
do $$
begin
  if not exists (select 1 from public.staff) then
    insert into public.staff (name, pin_access, contact_number, is_admin) values
      ('Admin User',  '1234', '+91-99001-00001', true),
      ('Staff Alpha', '5678', '+91-99001-00002', false);
  end if;
end $$;


-- ── 2. Tickets table ──────────────────────────────────────────────────────────
create table if not exists public.tickets (
  id                 bigint generated by default as identity primary key,
  issue_description  text        not null,
  location           text        not null,
  status             text        not null default 'open'
                        check (status in ('open', 'pending', 'resolved')),
  priority           text        not null default 'normal'
                        check (priority in ('low', 'normal', 'high', 'critical')),
  creator_name       text        not null,
  assigned_to        text,                  -- name or PIN of assignee
  created_at         timestamptz not null default now()
);

-- Ensure the issue_description check constraint exists on existing installations
do $$
begin
  if not exists (
    select 1 from pg_constraint 
    where conname = 'tickets_issue_description_check'
  ) then
    alter table public.tickets 
    add constraint tickets_issue_description_check 
    check (length(trim(issue_description)) > 0);
  end if;
end $$;

-- Add priority to existing installations
alter table public.tickets add column if not exists priority text not null default 'normal'
  check (priority in ('low', 'normal', 'high', 'critical'));


-- ── 3. Row Level Security ─────────────────────────────────────────────────────
-- Enable RLS on both tables
alter table public.staff   enable row level security;
alter table public.tickets enable row level security;

-- Staff Table Policies
-- Deny all public access to staff table (select/insert/update/delete)

-- Tickets Table Policies
drop policy if exists "tickets_insert_anon"    on public.tickets;
drop policy if exists "tickets_read_all"       on public.tickets;
drop policy if exists "tickets_update_creator" on public.tickets;

-- Anyone with the anon key can read tickets (staff feed is public within the app)
create policy "tickets_read_all" on public.tickets for select using (true);
-- ⛔ Direct INSERT blocked — must go through insert_ticket_secure() RPC
-- ⛔ Direct UPDATE blocked — must go through update_ticket_secure() RPC
-- Both RPCs verify the session token server-side before mutating data.


-- ── 4. Secure PIN Verification (RPC) ──────────────────────────────────────────
-- DROP first so return type can always be changed on re-runs
drop function if exists public.verify_staff_pin(text);
create or replace function public.verify_staff_pin(input_pin text)
returns table(id bigint, name text, is_admin boolean, contact_number text)
language sql security definer stable
as $$
  select id, name, is_admin, contact_number
  from public.staff
  where pin_access = crypt(input_pin, pin_access)
  limit 1;
$$;

-- Combined login: verify PIN + create session in a single round trip.
-- Returns token+name+is_admin on success, NULL row on bad PIN.
-- Halves login latency on slow/camp networks vs two sequential RPC calls.
drop function if exists public.login_staff(text);
create or replace function public.login_staff(input_pin text)
returns table(token text, name text, is_admin boolean)
language plpgsql security definer
as $$
declare
  v_staff public.staff%rowtype;
  v_token text;
begin
  select * into v_staff
  from public.staff
  where pin_access = crypt(input_pin, pin_access)
  limit 1;

  if v_staff.id is null then
    return; -- empty result = bad PIN
  end if;

  insert into public.sessions (staff_id)
  values (v_staff.id)
  returning sessions.token into v_token;

  return query select v_token, v_staff.name, v_staff.is_admin;
end;
$$;

-- ── 5. Server-side sessions ─────────────────────────────────────────────────
-- Only an opaque random token is stored client-side; all identity claims
-- are verified server-side on every app open.  localStorage tampering
-- cannot grant access because the token must exist in this table.
create table if not exists public.sessions (
  token      text        primary key
                           default encode(gen_random_bytes(32), 'hex'),
  staff_id   bigint      not null references public.staff(id) on delete cascade,
  expires_at timestamptz not null default now() + interval '12 hours',
  created_at timestamptz not null default now()
);

-- No direct client access to sessions table
alter table public.sessions enable row level security;

-- Called immediately after verify_staff_pin succeeds; returns the new token.
drop function if exists public.create_session(bigint);
create or replace function public.create_session(p_staff_id bigint)
returns text
language sql security definer
as $$
  insert into public.sessions (staff_id)
  values (p_staff_id)
  returning token;
$$;

-- Called on every app restore; returns name+is_admin only for a valid,
-- non-expired token — no client-supplied identity claims are trusted.
drop function if exists public.verify_session(text);
create or replace function public.verify_session(p_token text)
returns table(name text, is_admin boolean)
language sql security definer stable
as $$
  select st.name, st.is_admin
  from   public.sessions se
  join   public.staff    st on st.id = se.staff_id
  where  se.token      = p_token
    and  se.expires_at > now()
  limit 1;
$$;

-- Called on logout to immediately invalidate the token server-side.
drop function if exists public.delete_session(text);
create or replace function public.delete_session(p_token text)
returns void
language sql security definer
as $$
  delete from public.sessions where token = p_token;
$$;

-- ── 6. Secure ticket insert (session token required) ────────────────────────
-- Replaces the open tickets_insert_anon RLS policy.
-- Any authenticated staff member (valid session, any role) may submit a ticket.
drop function if exists public.insert_ticket_secure(text, text, text, text, text, text);
create or replace function public.insert_ticket_secure(
  p_token           text,
  p_description     text,
  p_location        text,
  p_priority        text    default 'normal',
  p_creator_name    text    default '',
  p_status          text    default 'open'
)
returns boolean
language plpgsql security definer
as $$
declare
  v_staff_id bigint;
begin
  -- Verify the token is valid and non-expired (any staff, not just admin)
  select se.staff_id into v_staff_id
  from   public.sessions se
  where  se.token      = p_token
    and  se.expires_at > now()
  limit 1;

  if v_staff_id is null then
    return false;
  end if;

  insert into public.tickets (issue_description, location, priority, creator_name, status)
  values (p_description, p_location, p_priority, p_creator_name, p_status);

  return true;
end;
$$;

-- ── 7. Secure ticket update (token + admin verified server-side) ────────────────
-- Replaces the open RLS UPDATE policy.  The anon key alone cannot update tickets.
-- Only a valid, non-expired session whose staff row has is_admin = true may update.
drop function if exists public.update_ticket_secure(text, bigint, text, text, text);
create or replace function public.update_ticket_secure(
  p_token       text,
  p_ticket_id   bigint,
  p_status      text    default null,
  p_priority    text    default null,
  p_assigned_to text    default null
)
returns boolean
language plpgsql security definer
as $$
declare
  v_is_admin boolean;
begin
  -- 1. Verify the session token is valid, non-expired, and belongs to an admin.
  select st.is_admin into v_is_admin
  from   public.sessions se
  join   public.staff    st on st.id = se.staff_id
  where  se.token      = p_token
    and  se.expires_at > now()
  limit 1;

  -- Reject if token missing / expired / not an admin
  if v_is_admin is null or not v_is_admin then
    return false;
  end if;

  -- 2. Perform the update using only the explicitly supplied fields.
  update public.tickets
  set
    status      = coalesce(p_status,      status),
    priority    = coalesce(p_priority,    priority),
    assigned_to = coalesce(p_assigned_to, assigned_to)
  where id = p_ticket_id;

  return found;
end;
$$;

-- ── 8. Secure PIN Reset (RPC) ─────────────────────────────────────────────────
create or replace function public.reset_staff_pin(staff_id bigint, new_pin text)
returns boolean
language plpgsql
security definer
as $$
begin
  -- Note: Trigger will automatically hash the new_pin
  update public.staff
  set pin_access = new_pin
  where id = staff_id;
  
  return found;
end;
$$;


-- ── 9. Enable Realtime on tickets ─────────────────────────────────────────────
do $$
begin
  if not exists (
    select 1 from pg_publication_tables 
    where pubname = 'supabase_realtime' 
    and schemaname = 'public' 
    and tablename = 'tickets'
  ) then
    alter publication supabase_realtime add table public.tickets;
  end if;
end $$;
